package controller;

public enum Event {
	BTN_CHAIN, BTN_WAREHOUSE, BTN_CHAIN_CONTINUE, BTN_BACK_MAIN_PANEL, BTN_CHAIN_CREATE, BTN_BACK_MENU_CHAIN, BTN_WAREHOUSE_CONTINUE, BTN_CREATE_PRODUCT, BTN_SEARCH_PRODUCTO, BTN_BACK_MENU_WAREHOUSE, BTN_QUANTIFIED_PRODUCTS, BTN_CALCULATE_INVENTARY_VALUE, BTN_REGISTER_SOLD_PRODUCT, BTN_SHOW_PRODUCTS_PS
}
